{
 "title": "Temperature & Humidity Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "label_values(pico_temperature_celsius, location)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(pico_temperature_celsius{location=\"$location\"}[5m])"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(pico_humidity_percent{location=\"$location\"}[5m])"
    }
   ]
  },
  {
   "title": "Humidity - $location",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pico_humidity_percent{location=~\"$location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Temperature - $location",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "pico_temperature_celsius{location=~\"$location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  }
 ]
}